server:
  port: 8001
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

spring:
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: customerservice
          predicates[0]: Path=/customerservice/api/v1/cities/**
          uri: lb://CUSTOMERSERVICE
        routes[1]:
          id: discoveryserver
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:8888

    
